// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Models;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(VerssclubContext))]
    [Migration("20240603132245_VerssClubDB")]
    partial class VerssClubDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KhachhangVoucher", b =>
                {
                    b.Property<int>("Makhachhang")
                        .HasColumnType("int")
                        .HasColumnName("MAKHACHHANG");

                    b.Property<int>("Mavoucher")
                        .HasColumnType("int")
                        .HasColumnName("MAVOUCHER");

                    b.HasKey("Makhachhang", "Mavoucher")
                        .HasName("PK__KHACHHAN__C56C958289A8B217");

                    b.HasIndex("Mavoucher");

                    b.ToTable("KHACHHANG_VOUCHER", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Chatlieu", b =>
                {
                    b.Property<int>("Machatlieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MACHATLIEU");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Machatlieu"));

                    b.Property<string>("Tenchatlieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENCHATLIEU");

                    b.HasKey("Machatlieu")
                        .HasName("PK__CHATLIEU__80F939F8409953CD");

                    b.ToTable("CHATLIEU", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Chucvu", b =>
                {
                    b.Property<int>("Machucvu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MACHUCVU");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Machucvu"));

                    b.Property<string>("Vaitro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("VAITRO");

                    b.HasKey("Machucvu")
                        .HasName("PK__CHUCVU__9FA9FD6A30F1A097");

                    b.ToTable("CHUCVU", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Danhgium", b =>
                {
                    b.Property<int>("Madanhgia")
                        .HasColumnType("int")
                        .HasColumnName("MADANHGIA");

                    b.Property<string>("Hinhanh")
                        .HasColumnType("text")
                        .HasColumnName("HINHANH");

                    b.Property<int?>("Makhachhang")
                        .HasColumnType("int")
                        .HasColumnName("MAKHACHHANG");

                    b.Property<int?>("Masanphamct")
                        .HasColumnType("int")
                        .HasColumnName("MASANPHAMCT");

                    b.Property<string>("Mota")
                        .HasColumnType("text")
                        .HasColumnName("MOTA");

                    b.Property<DateOnly?>("Ngaydang")
                        .HasColumnType("date")
                        .HasColumnName("NGAYDANG");

                    b.Property<int?>("Sosao")
                        .HasColumnType("int")
                        .HasColumnName("SOSAO");

                    b.HasKey("Madanhgia")
                        .HasName("PK__DANHGIA__8597D60A5B123A9C");

                    b.HasIndex("Makhachhang");

                    b.HasIndex("Masanphamct");

                    b.ToTable("DANHGIA", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Giamgium", b =>
                {
                    b.Property<int>("Magiamgia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAGIAMGIA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Magiamgia"));

                    b.Property<int>("Masanphamct")
                        .HasColumnType("int")
                        .HasColumnName("MASANPHAMCT");

                    b.Property<DateOnly>("Ngaybatdau")
                        .HasColumnType("date")
                        .HasColumnName("NGAYBATDAU");

                    b.Property<DateOnly>("Ngayketthuc")
                        .HasColumnType("date")
                        .HasColumnName("NGAYKETTHUC");

                    b.Property<DateTime>("Ngaytao")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYTAO");

                    b.Property<string>("Tengiamgia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENGIAMGIA");

                    b.Property<double>("Tilegiamgia")
                        .HasColumnType("float")
                        .HasColumnName("TILEGIAMGIA");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Magiamgia")
                        .HasName("PK__GIAMGIA__41C28439E7F89EE5");

                    b.HasIndex("Masanphamct");

                    b.ToTable("GIAMGIA", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Giohang", b =>
                {
                    b.Property<int>("Magiohang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAGIOHANG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Magiohang"));

                    b.Property<int?>("Makhachhang")
                        .HasColumnType("int")
                        .HasColumnName("MAKHACHHANG");

                    b.HasKey("Magiohang")
                        .HasName("PK__GIOHANG__559F5534FE45FFEA");

                    b.HasIndex("Makhachhang");

                    b.ToTable("GIOHANG", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Giohangct", b =>
                {
                    b.Property<int>("Magiohangct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAGIOHANGCT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Magiohangct"));

                    b.Property<int>("Magiohang")
                        .HasColumnType("int")
                        .HasColumnName("MAGIOHANG");

                    b.Property<int>("Makhachhang")
                        .HasColumnType("int")
                        .HasColumnName("MAKHACHHANG");

                    b.Property<int>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.Property<decimal>("Tongtien")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("TONGTIEN");

                    b.HasKey("Magiohangct")
                        .HasName("PK__GIOHANGC__9BEC54314D9966A1");

                    b.HasIndex("Magiohang");

                    b.ToTable("GIOHANGCT", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Hoadon", b =>
                {
                    b.Property<int>("Mahoadon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAHOADON");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mahoadon"));

                    b.Property<string>("Ghichu")
                        .HasColumnType("text")
                        .HasColumnName("GHICHU");

                    b.Property<int>("Makhachhang")
                        .HasColumnType("int")
                        .HasColumnName("MAKHACHHANG");

                    b.Property<int>("Manhanvien")
                        .HasColumnType("int")
                        .HasColumnName("MANHANVIEN");

                    b.Property<int>("Mavoucher")
                        .HasColumnType("int")
                        .HasColumnName("MAVOUCHER");

                    b.Property<DateOnly>("Ngaytao")
                        .HasColumnType("date")
                        .HasColumnName("NGAYTAO");

                    b.Property<decimal>("Tongtien")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("TONGTIEN");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Mahoadon")
                        .HasName("PK__HOADON__A4999DF5A99DB3FF");

                    b.HasIndex("Makhachhang");

                    b.HasIndex("Manhanvien");

                    b.HasIndex("Mavoucher");

                    b.ToTable("HOADON", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Hoadonct", b =>
                {
                    b.Property<int>("Mahoadonct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAHOADONCT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mahoadonct"));

                    b.Property<int>("Mahoadon")
                        .HasColumnType("int")
                        .HasColumnName("MAHOADON");

                    b.Property<int>("Masanphamct")
                        .HasColumnType("int")
                        .HasColumnName("MASANPHAMCT");

                    b.Property<int>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.Property<decimal>("Tongtien")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("TONGTIEN");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Mahoadonct")
                        .HasName("PK__HOADONCT__658D76744B544D7F");

                    b.HasIndex("Mahoadon");

                    b.HasIndex("Masanphamct");

                    b.ToTable("HOADONCT", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Khachhang", b =>
                {
                    b.Property<int>("Makhachhang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAKHACHHANG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Makhachhang"));

                    b.Property<string>("Diachi")
                        .HasColumnType("text")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<bool?>("Gioitinh")
                        .HasColumnType("bit")
                        .HasColumnName("GIOITINH");

                    b.Property<string>("Matkhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MATKHAU");

                    b.Property<DateOnly?>("Ngaysinh")
                        .HasColumnType("date")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SDT");

                    b.Property<string>("Tenkhachhang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENKHACHHANG");

                    b.HasKey("Makhachhang")
                        .HasName("PK__KHACHHAN__30035C2FBAF71AB2");

                    b.ToTable("KHACHHANG", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Loaimau", b =>
                {
                    b.Property<int>("Mamau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAMAU");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mamau"));

                    b.Property<string>("Tenmau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENMAU");

                    b.HasKey("Mamau")
                        .HasName("PK__LOAIMAU__7B7346CFE972F6BC");

                    b.ToTable("LOAIMAU", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Loaisanpham", b =>
                {
                    b.Property<int>("Maloaisanpham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MALOAISANPHAM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Maloaisanpham"));

                    b.Property<string>("Tenloai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENLOAI");

                    b.HasKey("Maloaisanpham")
                        .HasName("PK__LOAISANP__F22DB2996F257290");

                    b.ToTable("LOAISANPHAM", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Nhanvien", b =>
                {
                    b.Property<int>("Manhanvien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MANHANVIEN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Manhanvien"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<int?>("Machucvu")
                        .HasColumnType("int")
                        .HasColumnName("MACHUCVU");

                    b.Property<string>("Matkhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MATKHAU");

                    b.Property<int?>("Namsinh")
                        .HasColumnType("int")
                        .HasColumnName("NAMSINH");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SDT");

                    b.Property<string>("Tennhanvien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENNHANVIEN");

                    b.Property<bool?>("Trangthai")
                        .HasColumnType("bit")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Manhanvien")
                        .HasName("PK__NHANVIEN__7E46DD91D3C3DD91");

                    b.HasIndex("Machucvu");

                    b.ToTable("NHANVIEN", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Order", b =>
                {
                    b.Property<int>("Maorder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAORDER");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Maorder"));

                    b.Property<int>("Magiohangct")
                        .HasColumnType("int")
                        .HasColumnName("MAGIOHANGCT");

                    b.Property<int>("Manhanvien")
                        .HasColumnType("int")
                        .HasColumnName("MANHANVIEN");

                    b.Property<DateOnly>("Ngaydathang")
                        .HasColumnType("date")
                        .HasColumnName("NGAYDATHANG");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Maorder")
                        .HasName("PK__ORDER__C836154144ACBD5A");

                    b.HasIndex("Magiohangct");

                    b.HasIndex("Manhanvien");

                    b.ToTable("ORDER", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Sanpham", b =>
                {
                    b.Property<int>("Masanpham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MASANPHAM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Masanpham"));

                    b.Property<int>("Machatlieu")
                        .HasColumnType("int")
                        .HasColumnName("MACHATLIEU");

                    b.Property<int>("Magiohangct")
                        .HasColumnType("int")
                        .HasColumnName("MAGIOHANGCT");

                    b.Property<int>("Maloaisanpham")
                        .HasColumnType("int")
                        .HasColumnName("MALOAISANPHAM");

                    b.Property<int>("Mathuonghieu")
                        .HasColumnType("int")
                        .HasColumnName("MATHUONGHIEU");

                    b.Property<int>("Maxuatxu")
                        .HasColumnType("int")
                        .HasColumnName("MAXUATXU");

                    b.Property<string>("Tensanpham")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENSANPHAM");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Masanpham")
                        .HasName("PK__SANPHAM__9534C89206358B7F");

                    b.HasIndex("Machatlieu");

                    b.HasIndex("Magiohangct");

                    b.HasIndex("Maloaisanpham");

                    b.HasIndex("Mathuonghieu");

                    b.HasIndex("Maxuatxu");

                    b.ToTable("SANPHAM", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Sanphamct", b =>
                {
                    b.Property<int>("Masanphamct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MASANPHAMCT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Masanphamct"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("GIA");

                    b.Property<string>("Imgurl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("IMGURL");

                    b.Property<int>("Machatlieu")
                        .HasColumnType("int")
                        .HasColumnName("MACHATLIEU");

                    b.Property<int>("Maloaisanpham")
                        .HasColumnType("int")
                        .HasColumnName("MALOAISANPHAM");

                    b.Property<int>("Mamau")
                        .HasColumnType("int")
                        .HasColumnName("MAMAU");

                    b.Property<int>("Masanpham")
                        .HasColumnType("int")
                        .HasColumnName("MASANPHAM");

                    b.Property<int>("Masize")
                        .HasColumnType("int")
                        .HasColumnName("MASIZE");

                    b.Property<int>("Mathuonghieu")
                        .HasColumnType("int")
                        .HasColumnName("MATHUONGHIEU");

                    b.Property<int>("Maxuatxu")
                        .HasColumnType("int")
                        .HasColumnName("MAXUATXU");

                    b.Property<int>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.Property<string>("Tensanphamct")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENSANPHAMCT");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Masanphamct")
                        .HasName("PK__SANPHAMC__E932BBBC8E57A655");

                    b.HasIndex("Machatlieu");

                    b.HasIndex("Maloaisanpham");

                    b.HasIndex("Mamau");

                    b.HasIndex("Masanpham");

                    b.HasIndex("Masize");

                    b.HasIndex("Mathuonghieu");

                    b.HasIndex("Maxuatxu");

                    b.ToTable("SANPHAMCT", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Size", b =>
                {
                    b.Property<int>("Masize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MASIZE");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Masize"));

                    b.Property<int>("Size1")
                        .HasColumnType("int")
                        .HasColumnName("SIZE");

                    b.HasKey("Masize")
                        .HasName("PK__SIZE__3DD4402B59BB3D12");

                    b.ToTable("SIZE", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Thanhtoan", b =>
                {
                    b.Property<int>("Mathanhtoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MATHANHTOAN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mathanhtoan"));

                    b.Property<int>("Mahoadon")
                        .HasColumnType("int")
                        .HasColumnName("MAHOADON");

                    b.Property<DateOnly>("Ngaythanhtoan")
                        .HasColumnType("date")
                        .HasColumnName("NGAYTHANHTOAN");

                    b.Property<int>("Phuongthucthanhtoan")
                        .HasColumnType("int")
                        .HasColumnName("PHUONGTHUCTHANHTOAN");

                    b.Property<decimal>("Tongtien")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("TONGTIEN");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Mathanhtoan")
                        .HasName("PK__THANHTOA__E5D8225C7887F3AC");

                    b.HasIndex("Mahoadon");

                    b.ToTable("THANHTOAN", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Thuonghieu", b =>
                {
                    b.Property<int>("Mathuonghieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MATHUONGHIEU");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mathuonghieu"));

                    b.Property<string>("Tenthuonghieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENTHUONGHIEU");

                    b.HasKey("Mathuonghieu")
                        .HasName("PK__THUONGHI__B319F638DA1374F8");

                    b.ToTable("THUONGHIEU", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Voucher", b =>
                {
                    b.Property<int>("Mavoucher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAVOUCHER");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mavoucher"));

                    b.Property<DateOnly>("Ngaybatdau")
                        .HasColumnType("date")
                        .HasColumnName("NGAYBATDAU");

                    b.Property<DateOnly>("Ngayketthuc")
                        .HasColumnType("date")
                        .HasColumnName("NGAYKETTHUC");

                    b.Property<DateOnly>("Ngaytao")
                        .HasColumnType("date")
                        .HasColumnName("NGAYTAO");

                    b.Property<double?>("Phantramgiam")
                        .HasColumnType("float")
                        .HasColumnName("PHANTRAMGIAM");

                    b.Property<string>("Tenvoucher")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TENVOUCHER");

                    b.Property<bool?>("Trangthai")
                        .HasColumnType("bit")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Mavoucher")
                        .HasName("PK__VOUCHER__56FC9ADE1ADA7F35");

                    b.ToTable("VOUCHER", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Xuatxu", b =>
                {
                    b.Property<int>("Maxuatxu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAXUATXU");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Maxuatxu"));

                    b.Property<string>("Diadiemxuatxu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DIADIEMXUATXU");

                    b.HasKey("Maxuatxu")
                        .HasName("PK__XUATXU__52D93EA2009C47ED");

                    b.ToTable("XUATXU", (string)null);
                });

            modelBuilder.Entity("KhachhangVoucher", b =>
                {
                    b.HasOne("Repository.Models.Khachhang", null)
                        .WithMany()
                        .HasForeignKey("Makhachhang")
                        .IsRequired()
                        .HasConstraintName("FK__KHACHHANG__MAKHA__3E52440B");

                    b.HasOne("Repository.Models.Voucher", null)
                        .WithMany()
                        .HasForeignKey("Mavoucher")
                        .IsRequired()
                        .HasConstraintName("FK__KHACHHANG__MAVOU__3F466844");
                });

            modelBuilder.Entity("Repository.Models.Danhgium", b =>
                {
                    b.HasOne("Repository.Models.Khachhang", "MakhachhangNavigation")
                        .WithMany("Danhgia")
                        .HasForeignKey("Makhachhang")
                        .HasConstraintName("FK__DANHGIA__MAKHACH__6477ECF3");

                    b.HasOne("Repository.Models.Sanphamct", "MasanphamctNavigation")
                        .WithMany("Danhgia")
                        .HasForeignKey("Masanphamct")
                        .HasConstraintName("FK__DANHGIA__MASANPH__6383C8BA");

                    b.Navigation("MakhachhangNavigation");

                    b.Navigation("MasanphamctNavigation");
                });

            modelBuilder.Entity("Repository.Models.Giamgium", b =>
                {
                    b.HasOne("Repository.Models.Sanphamct", "MasanphamctNavigation")
                        .WithMany("Giamgia")
                        .HasForeignKey("Masanphamct")
                        .IsRequired()
                        .HasConstraintName("FK__GIAMGIA__MASANPH__59063A47");

                    b.Navigation("MasanphamctNavigation");
                });

            modelBuilder.Entity("Repository.Models.Giohang", b =>
                {
                    b.HasOne("Repository.Models.Khachhang", "MakhachhangNavigation")
                        .WithMany("Giohangs")
                        .HasForeignKey("Makhachhang")
                        .HasConstraintName("FK__GIOHANG__MAKHACH__36B12243");

                    b.Navigation("MakhachhangNavigation");
                });

            modelBuilder.Entity("Repository.Models.Giohangct", b =>
                {
                    b.HasOne("Repository.Models.Giohang", "MagiohangNavigation")
                        .WithMany("Giohangcts")
                        .HasForeignKey("Magiohang")
                        .IsRequired()
                        .HasConstraintName("FK__GIOHANGCT__MAGIO__398D8EEE");

                    b.Navigation("MagiohangNavigation");
                });

            modelBuilder.Entity("Repository.Models.Hoadon", b =>
                {
                    b.HasOne("Repository.Models.Khachhang", "MakhachhangNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("Makhachhang")
                        .IsRequired()
                        .HasConstraintName("FK__HOADON__TONGTIEN__4222D4EF");

                    b.HasOne("Repository.Models.Nhanvien", "ManhanvienNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("Manhanvien")
                        .IsRequired()
                        .HasConstraintName("FK__HOADON__MANHANVI__4316F928");

                    b.HasOne("Repository.Models.Voucher", "MavoucherNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("Mavoucher")
                        .IsRequired()
                        .HasConstraintName("FK__HOADON__MAVOUCHE__440B1D61");

                    b.Navigation("MakhachhangNavigation");

                    b.Navigation("ManhanvienNavigation");

                    b.Navigation("MavoucherNavigation");
                });

            modelBuilder.Entity("Repository.Models.Hoadonct", b =>
                {
                    b.HasOne("Repository.Models.Hoadon", "MahoadonNavigation")
                        .WithMany("Hoadoncts")
                        .HasForeignKey("Mahoadon")
                        .IsRequired()
                        .HasConstraintName("FK__HOADONCT__MAHOAD__5BE2A6F2");

                    b.HasOne("Repository.Models.Sanphamct", "MasanphamctNavigation")
                        .WithMany("Hoadoncts")
                        .HasForeignKey("Masanphamct")
                        .IsRequired()
                        .HasConstraintName("FK__HOADONCT__MASANP__5CD6CB2B");

                    b.Navigation("MahoadonNavigation");

                    b.Navigation("MasanphamctNavigation");
                });

            modelBuilder.Entity("Repository.Models.Nhanvien", b =>
                {
                    b.HasOne("Repository.Models.Chucvu", "MachucvuNavigation")
                        .WithMany("Nhanviens")
                        .HasForeignKey("Machucvu")
                        .HasConstraintName("FK_CHUCVU");

                    b.Navigation("MachucvuNavigation");
                });

            modelBuilder.Entity("Repository.Models.Order", b =>
                {
                    b.HasOne("Repository.Models.Giohangct", "MagiohangctNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("Magiohangct")
                        .IsRequired()
                        .HasConstraintName("FK__ORDER__MAGIOHANG__60A75C0F");

                    b.HasOne("Repository.Models.Nhanvien", "ManhanvienNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("Manhanvien")
                        .IsRequired()
                        .HasConstraintName("FK__ORDER__MANHANVIE__5FB337D6");

                    b.Navigation("MagiohangctNavigation");

                    b.Navigation("ManhanvienNavigation");
                });

            modelBuilder.Entity("Repository.Models.Sanpham", b =>
                {
                    b.HasOne("Repository.Models.Chatlieu", "MachatlieuNavigation")
                        .WithMany("Sanphams")
                        .HasForeignKey("Machatlieu")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAM__MACHATL__4AB81AF0");

                    b.HasOne("Repository.Models.Giohangct", "MagiohangctNavigation")
                        .WithMany("Sanphams")
                        .HasForeignKey("Magiohangct")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAM__MAGIOHA__49C3F6B7");

                    b.HasOne("Repository.Models.Loaisanpham", "MaloaisanphamNavigation")
                        .WithMany("Sanphams")
                        .HasForeignKey("Maloaisanpham")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAM__MALOAIS__4D94879B");

                    b.HasOne("Repository.Models.Thuonghieu", "MathuonghieuNavigation")
                        .WithMany("Sanphams")
                        .HasForeignKey("Mathuonghieu")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAM__MATHUON__4CA06362");

                    b.HasOne("Repository.Models.Xuatxu", "MaxuatxuNavigation")
                        .WithMany("Sanphams")
                        .HasForeignKey("Maxuatxu")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAM__MAXUATX__4BAC3F29");

                    b.Navigation("MachatlieuNavigation");

                    b.Navigation("MagiohangctNavigation");

                    b.Navigation("MaloaisanphamNavigation");

                    b.Navigation("MathuonghieuNavigation");

                    b.Navigation("MaxuatxuNavigation");
                });

            modelBuilder.Entity("Repository.Models.Sanphamct", b =>
                {
                    b.HasOne("Repository.Models.Chatlieu", "MachatlieuNavigation")
                        .WithMany("Sanphamcts")
                        .HasForeignKey("Machatlieu")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAMCT__MACHA__5070F446");

                    b.HasOne("Repository.Models.Loaisanpham", "MaloaisanphamNavigation")
                        .WithMany("Sanphamcts")
                        .HasForeignKey("Maloaisanpham")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAMCT__MALOA__5535A963");

                    b.HasOne("Repository.Models.Loaimau", "MamauNavigation")
                        .WithMany("Sanphamcts")
                        .HasForeignKey("Mamau")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAMCT__MAMAU__5165187F");

                    b.HasOne("Repository.Models.Sanpham", "MasanphamNavigation")
                        .WithMany("Sanphamcts")
                        .HasForeignKey("Masanpham")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAMCT__MASAN__52593CB8");

                    b.HasOne("Repository.Models.Size", "MasizeNavigation")
                        .WithMany("Sanphamcts")
                        .HasForeignKey("Masize")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAMCT__MASIZ__5629CD9C");

                    b.HasOne("Repository.Models.Voucher", "MathuonghieuNavigation")
                        .WithMany("Sanphamcts")
                        .HasForeignKey("Mathuonghieu")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAMCT__MATHU__5441852A");

                    b.HasOne("Repository.Models.Xuatxu", "MaxuatxuNavigation")
                        .WithMany("Sanphamcts")
                        .HasForeignKey("Maxuatxu")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAMCT__MAXUA__534D60F1");

                    b.Navigation("MachatlieuNavigation");

                    b.Navigation("MaloaisanphamNavigation");

                    b.Navigation("MamauNavigation");

                    b.Navigation("MasanphamNavigation");

                    b.Navigation("MasizeNavigation");

                    b.Navigation("MathuonghieuNavigation");

                    b.Navigation("MaxuatxuNavigation");
                });

            modelBuilder.Entity("Repository.Models.Thanhtoan", b =>
                {
                    b.HasOne("Repository.Models.Hoadon", "MahoadonNavigation")
                        .WithMany("Thanhtoans")
                        .HasForeignKey("Mahoadon")
                        .IsRequired()
                        .HasConstraintName("FK__THANHTOAN__TONGT__46E78A0C");

                    b.Navigation("MahoadonNavigation");
                });

            modelBuilder.Entity("Repository.Models.Chatlieu", b =>
                {
                    b.Navigation("Sanphamcts");

                    b.Navigation("Sanphams");
                });

            modelBuilder.Entity("Repository.Models.Chucvu", b =>
                {
                    b.Navigation("Nhanviens");
                });

            modelBuilder.Entity("Repository.Models.Giohang", b =>
                {
                    b.Navigation("Giohangcts");
                });

            modelBuilder.Entity("Repository.Models.Giohangct", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Sanphams");
                });

            modelBuilder.Entity("Repository.Models.Hoadon", b =>
                {
                    b.Navigation("Hoadoncts");

                    b.Navigation("Thanhtoans");
                });

            modelBuilder.Entity("Repository.Models.Khachhang", b =>
                {
                    b.Navigation("Danhgia");

                    b.Navigation("Giohangs");

                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("Repository.Models.Loaimau", b =>
                {
                    b.Navigation("Sanphamcts");
                });

            modelBuilder.Entity("Repository.Models.Loaisanpham", b =>
                {
                    b.Navigation("Sanphamcts");

                    b.Navigation("Sanphams");
                });

            modelBuilder.Entity("Repository.Models.Nhanvien", b =>
                {
                    b.Navigation("Hoadons");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Repository.Models.Sanpham", b =>
                {
                    b.Navigation("Sanphamcts");
                });

            modelBuilder.Entity("Repository.Models.Sanphamct", b =>
                {
                    b.Navigation("Danhgia");

                    b.Navigation("Giamgia");

                    b.Navigation("Hoadoncts");
                });

            modelBuilder.Entity("Repository.Models.Size", b =>
                {
                    b.Navigation("Sanphamcts");
                });

            modelBuilder.Entity("Repository.Models.Thuonghieu", b =>
                {
                    b.Navigation("Sanphams");
                });

            modelBuilder.Entity("Repository.Models.Voucher", b =>
                {
                    b.Navigation("Hoadons");

                    b.Navigation("Sanphamcts");
                });

            modelBuilder.Entity("Repository.Models.Xuatxu", b =>
                {
                    b.Navigation("Sanphamcts");

                    b.Navigation("Sanphams");
                });
#pragma warning restore 612, 618
        }
    }
}
