// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Models;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(VerssclubContext))]
    partial class VerssclubContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Khachhangvoucher", b =>
                {
                    b.Property<string>("Makh")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MAKH");

                    b.Property<string>("Magiamgia")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MAGIAMGIA");

                    b.HasKey("Makh", "Magiamgia");

                    b.HasIndex("Magiamgia");

                    b.ToTable("KHACHHANGVOUCHER", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Chatlieu", b =>
                {
                    b.Property<string>("Machatlieu")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MACHATLIEU");

                    b.Property<string>("Tenchatlieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENCHATLIEU");

                    b.HasKey("Machatlieu")
                        .HasName("PK__CHATLIEU__80F939F813A47416");

                    b.ToTable("CHATLIEU", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Chucvu", b =>
                {
                    b.Property<string>("Machucvu")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MACHUCVU");

                    b.Property<string>("Vaitro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("VAITRO");

                    b.HasKey("Machucvu")
                        .HasName("PK__CHUCVU__9FA9FD6A7CBD95BE");

                    b.ToTable("CHUCVU", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Danhgium", b =>
                {
                    b.Property<string>("Madanhgia")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MADANHGIA");

                    b.Property<string>("Binhluan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BINHLUAN");

                    b.Property<string>("Hinhanh")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("HINHANH");

                    b.Property<string>("Makh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MAKH");

                    b.Property<string>("Maspct")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MASPCT");

                    b.Property<DateOnly>("Ngaydang")
                        .HasColumnType("date")
                        .HasColumnName("NGAYDANG");

                    b.Property<int?>("Sosao")
                        .HasColumnType("int")
                        .HasColumnName("SOSAO");

                    b.HasKey("Madanhgia")
                        .HasName("PK__DANHGIA__8597D60A7BE0A90B");

                    b.HasIndex("Makh");

                    b.HasIndex("Maspct");

                    b.ToTable("DANHGIA", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Giohang", b =>
                {
                    b.Property<string>("Makh")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MAKH");

                    b.HasKey("Makh")
                        .HasName("PK__GIOHANG__603F592CB7F9DAF2");

                    b.ToTable("GIOHANG", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Giohangct", b =>
                {
                    b.Property<string>("Maghct")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MAGHCT");

                    b.Property<string>("Makh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MAKH");

                    b.Property<string>("Maspct")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MASPCT");

                    b.Property<int>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.Property<double>("Tongtien")
                        .HasColumnType("float")
                        .HasColumnName("TONGTIEN");

                    b.HasKey("Maghct")
                        .HasName("PK__GIOHANGC__0CCE71FE27BF5E53");

                    b.HasIndex("Makh");

                    b.HasIndex("Maspct");

                    b.ToTable("GIOHANGCT", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Hoadon", b =>
                {
                    b.Property<string>("Mahd")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MAHD");

                    b.Property<string>("Ghichu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("GHICHU");

                    b.Property<string>("Magiamgia")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MAGIAMGIA");

                    b.Property<string>("Makh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MAKH");

                    b.Property<string>("Manv")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MANV");

                    b.Property<DateTime>("Ngaytao")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYTAO");

                    b.Property<double>("Tongtien")
                        .HasColumnType("float")
                        .HasColumnName("TONGTIEN");

                    b.Property<string>("Trangthai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Mahd")
                        .HasName("PK__HOADON__603F20CE82D3DF24");

                    b.HasIndex("Magiamgia");

                    b.HasIndex("Makh");

                    b.HasIndex("Manv");

                    b.ToTable("HOADON", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Hoadonct", b =>
                {
                    b.Property<string>("Mahdct")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MAHDCT");

                    b.Property<string>("Mahd")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MAHD");

                    b.Property<string>("Maspct")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MASPCT");

                    b.Property<double>("Soluong")
                        .HasColumnType("float")
                        .HasColumnName("SOLUONG");

                    b.Property<double>("Tongtien")
                        .HasColumnType("float")
                        .HasColumnName("TONGTIEN");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Mahdct")
                        .HasName("PK__HOADONCT__1A700082BC549E62");

                    b.HasIndex("Mahd");

                    b.HasIndex("Maspct");

                    b.ToTable("HOADONCT", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Khachhang", b =>
                {
                    b.Property<string>("Makh")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MAKH");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Email")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("EMAIL");

                    b.Property<bool>("Gioitinh")
                        .HasColumnType("bit")
                        .HasColumnName("GIOITINH");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HOTEN");

                    b.Property<string>("Matkhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MATKHAU");

                    b.Property<DateOnly>("Ngaysinh")
                        .HasColumnType("date")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SDT");

                    b.HasKey("Makh")
                        .HasName("PK__KHACHHAN__603F592C6C33E491");

                    b.ToTable("KHACHHANG", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Loai", b =>
                {
                    b.Property<string>("Maloai")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MALOAI");

                    b.Property<string>("Tenloai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENLOAI");

                    b.HasKey("Maloai")
                        .HasName("PK__LOAI__2F633F23A1F0FFF5");

                    b.ToTable("LOAI", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Mau", b =>
                {
                    b.Property<string>("Mamau")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MAMAU");

                    b.Property<string>("Mau1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MAU");

                    b.HasKey("Mamau")
                        .HasName("PK__MAU__7B7346CF71E376BB");

                    b.ToTable("MAU", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Nhanvien", b =>
                {
                    b.Property<string>("Manv")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MANV");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Email")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("EMAIL");

                    b.Property<bool>("Gioitinh")
                        .HasColumnType("bit")
                        .HasColumnName("GIOITINH");

                    b.Property<string>("Machucvu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MACHUCVU");

                    b.Property<string>("Matkhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MATKHAU");

                    b.Property<DateOnly>("Ngaysinh")
                        .HasColumnType("date")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SDT");

                    b.Property<string>("Tenkhachhang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENKHACHHANG");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Manv")
                        .HasName("PK__NHANVIEN__603F511490E3C095");

                    b.HasIndex("Machucvu");

                    b.ToTable("NHANVIEN", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Order", b =>
                {
                    b.Property<string>("Maorder")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MAORDER");

                    b.Property<string>("Maghct")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MAGHCT");

                    b.Property<string>("Manv")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MANV");

                    b.Property<DateTime>("Ngaydat")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYDAT");

                    b.Property<double>("Tongtien")
                        .HasColumnType("float")
                        .HasColumnName("TONGTIEN");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Maorder")
                        .HasName("PK__ORDER__C8361541EDBF2273");

                    b.HasIndex("Maghct");

                    b.HasIndex("Manv");

                    b.ToTable("ORDER", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Productdiscount", b =>
                {
                    b.Property<string>("Madiscounts")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MADISCOUNTS");

                    b.Property<DateTime>("Batdau")
                        .HasColumnType("datetime")
                        .HasColumnName("BATDAU");

                    b.Property<string>("Discountsname")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("DISCOUNTSNAME");

                    b.Property<DateTime>("Ketthuc")
                        .HasColumnType("datetime")
                        .HasColumnName("KETTHUC");

                    b.Property<string>("Maspct")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MASPCT");

                    b.Property<double>("Phamtramgiam")
                        .HasColumnType("float")
                        .HasColumnName("PHAMTRAMGIAM");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Madiscounts")
                        .HasName("PK__PRODUCTD__CC3E72D0C63B4F46");

                    b.HasIndex("Maspct");

                    b.ToTable("PRODUCTDISCOUNTS", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Sanpham", b =>
                {
                    b.Property<string>("Masp")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MASP");

                    b.Property<string>("Tensp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENSP");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Masp")
                        .HasName("PK__SANPHAM__60228A32309B7F3D");

                    b.ToTable("SANPHAM", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Sanphamct", b =>
                {
                    b.Property<string>("Maspct")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MASPCT");

                    b.Property<double>("Gia")
                        .HasColumnType("float")
                        .HasColumnName("GIA");

                    b.Property<string>("Imgurl")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("IMGURL");

                    b.Property<string>("Machatlieu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MACHATLIEU");

                    b.Property<string>("Maloai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MALOAI");

                    b.Property<string>("Mamau")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MAMAU");

                    b.Property<string>("Masize")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MASIZE");

                    b.Property<string>("Masp")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MASP");

                    b.Property<string>("Mathuonghieu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MATHUONGHIEU");

                    b.Property<string>("Maxuatxu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MAXUATXU");

                    b.Property<int>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Maspct")
                        .HasName("PK__SANPHAMC__3D158D86DA3BE69C");

                    b.HasIndex("Machatlieu");

                    b.HasIndex("Maloai");

                    b.HasIndex("Mamau");

                    b.HasIndex("Masize");

                    b.HasIndex("Masp");

                    b.HasIndex("Mathuonghieu");

                    b.HasIndex("Maxuatxu");

                    b.ToTable("SANPHAMCT", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Size", b =>
                {
                    b.Property<string>("Masize")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MASIZE");

                    b.Property<string>("Size1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SIZE");

                    b.HasKey("Masize")
                        .HasName("PK__SIZE__3DD4402B638DA858");

                    b.ToTable("SIZE", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Thanhtoan", b =>
                {
                    b.Property<string>("Mathanhtoan")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MATHANHTOAN");

                    b.Property<string>("Mahd")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MAHD");

                    b.Property<DateTime>("Ngaythanhtoan")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYTHANHTOAN");

                    b.Property<string>("Phuongthuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PHUONGTHUC");

                    b.Property<double>("Tongtien")
                        .HasColumnType("float")
                        .HasColumnName("TONGTIEN");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Mathanhtoan")
                        .HasName("PK__THANHTOA__E5D8225C0FB93A6A");

                    b.HasIndex("Mahd");

                    b.ToTable("THANHTOAN", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Thuonghieu", b =>
                {
                    b.Property<string>("Mathuonghieu")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MATHUONGHIEU");

                    b.Property<string>("Tenthuonghieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENTHUONGHIEU");

                    b.HasKey("Mathuonghieu")
                        .HasName("PK__THUONGHI__B319F6385EF447F9");

                    b.ToTable("THUONGHIEU", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Voucher", b =>
                {
                    b.Property<string>("Magiamgia")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MAGIAMGIA");

                    b.Property<DateTime>("Batdau")
                        .HasColumnType("datetime")
                        .HasColumnName("BATDAU");

                    b.Property<DateTime>("Ketthuc")
                        .HasColumnType("datetime")
                        .HasColumnName("KETTHUC");

                    b.Property<double>("Phantramgiam")
                        .HasColumnType("float")
                        .HasColumnName("PHANTRAMGIAM");

                    b.Property<string>("Tenma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENMA");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Magiamgia")
                        .HasName("PK__VOUCHER__41C28439EE4D6FBD");

                    b.ToTable("VOUCHER", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Xuatxu", b =>
                {
                    b.Property<string>("Maxuatxu")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MAXUATXU");

                    b.Property<string>("Xuatxu1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("XUATXU");

                    b.HasKey("Maxuatxu")
                        .HasName("PK__XUATXU__52D93EA2D573971E");

                    b.ToTable("XUATXU", (string)null);
                });

            modelBuilder.Entity("Khachhangvoucher", b =>
                {
                    b.HasOne("Repository.Models.Voucher", null)
                        .WithMany()
                        .HasForeignKey("Magiamgia")
                        .IsRequired()
                        .HasConstraintName("FK_KHACHHANGVOUCHER_VOUCHER");

                    b.HasOne("Repository.Models.Khachhang", null)
                        .WithMany()
                        .HasForeignKey("Makh")
                        .IsRequired()
                        .HasConstraintName("FK_KHACHHANGVOUCHER_KHACHHANG");
                });

            modelBuilder.Entity("Repository.Models.Danhgium", b =>
                {
                    b.HasOne("Repository.Models.Khachhang", "MakhNavigation")
                        .WithMany("Danhgia")
                        .HasForeignKey("Makh")
                        .IsRequired()
                        .HasConstraintName("FK__DANHGIA__MAKH__1BC821DD");

                    b.HasOne("Repository.Models.Sanphamct", "MaspctNavigation")
                        .WithMany("Danhgia")
                        .HasForeignKey("Maspct")
                        .IsRequired()
                        .HasConstraintName("FK__DANHGIA__MASPCT__1CBC4616");

                    b.Navigation("MakhNavigation");

                    b.Navigation("MaspctNavigation");
                });

            modelBuilder.Entity("Repository.Models.Giohang", b =>
                {
                    b.HasOne("Repository.Models.Khachhang", "MakhNavigation")
                        .WithOne("Giohang")
                        .HasForeignKey("Repository.Models.Giohang", "Makh")
                        .IsRequired()
                        .HasConstraintName("FK_GIOHANG_KHACHHANG");

                    b.Navigation("MakhNavigation");
                });

            modelBuilder.Entity("Repository.Models.Giohangct", b =>
                {
                    b.HasOne("Repository.Models.Khachhang", "MakhNavigation")
                        .WithMany("Giohangcts")
                        .HasForeignKey("Makh")
                        .IsRequired()
                        .HasConstraintName("FK__GIOHANGCT__MAKH__123EB7A3");

                    b.HasOne("Repository.Models.Sanphamct", "MaspctNavigation")
                        .WithMany("Giohangcts")
                        .HasForeignKey("Maspct")
                        .IsRequired()
                        .HasConstraintName("FK__GIOHANGCT__MASPC__1332DBDC");

                    b.Navigation("MakhNavigation");

                    b.Navigation("MaspctNavigation");
                });

            modelBuilder.Entity("Repository.Models.Hoadon", b =>
                {
                    b.HasOne("Repository.Models.Voucher", "MagiamgiaNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("Magiamgia")
                        .IsRequired()
                        .HasConstraintName("FK__HOADON__MAGIAMGI__25518C17");

                    b.HasOne("Repository.Models.Khachhang", "MakhNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("Makh")
                        .IsRequired()
                        .HasConstraintName("FK__HOADON__MAKH__236943A5");

                    b.HasOne("Repository.Models.Nhanvien", "ManvNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("Manv")
                        .IsRequired()
                        .HasConstraintName("FK__HOADON__MANV__245D67DE");

                    b.Navigation("MagiamgiaNavigation");

                    b.Navigation("MakhNavigation");

                    b.Navigation("ManvNavigation");
                });

            modelBuilder.Entity("Repository.Models.Hoadonct", b =>
                {
                    b.HasOne("Repository.Models.Hoadon", "MahdNavigation")
                        .WithMany("Hoadoncts")
                        .HasForeignKey("Mahd")
                        .IsRequired()
                        .HasConstraintName("FK__HOADONCT__MAHD__282DF8C2");

                    b.HasOne("Repository.Models.Sanphamct", "MaspctNavigation")
                        .WithMany("Hoadoncts")
                        .HasForeignKey("Maspct")
                        .IsRequired()
                        .HasConstraintName("FK__HOADONCT__MASPCT__29221CFB");

                    b.Navigation("MahdNavigation");

                    b.Navigation("MaspctNavigation");
                });

            modelBuilder.Entity("Repository.Models.Nhanvien", b =>
                {
                    b.HasOne("Repository.Models.Chucvu", "MachucvuNavigation")
                        .WithMany("Nhanviens")
                        .HasForeignKey("Machucvu")
                        .IsRequired()
                        .HasConstraintName("FK__NHANVIEN__MACHUC__778AC167");

                    b.Navigation("MachucvuNavigation");
                });

            modelBuilder.Entity("Repository.Models.Order", b =>
                {
                    b.HasOne("Repository.Models.Giohangct", "MaghctNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("Maghct")
                        .IsRequired()
                        .HasConstraintName("FK__ORDER__MAGHCT__1F98B2C1");

                    b.HasOne("Repository.Models.Nhanvien", "ManvNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("Manv")
                        .IsRequired()
                        .HasConstraintName("FK__ORDER__MANV__208CD6FA");

                    b.Navigation("MaghctNavigation");

                    b.Navigation("ManvNavigation");
                });

            modelBuilder.Entity("Repository.Models.Productdiscount", b =>
                {
                    b.HasOne("Repository.Models.Sanphamct", "MaspctNavigation")
                        .WithMany("Productdiscounts")
                        .HasForeignKey("Maspct")
                        .IsRequired()
                        .HasConstraintName("FK__PRODUCTDI__MASPC__2EDAF651");

                    b.Navigation("MaspctNavigation");
                });

            modelBuilder.Entity("Repository.Models.Sanphamct", b =>
                {
                    b.HasOne("Repository.Models.Chatlieu", "MachatlieuNavigation")
                        .WithMany("Sanphamcts")
                        .HasForeignKey("Machatlieu")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAMCT__MACHA__07C12930");

                    b.HasOne("Repository.Models.Loai", "MaloaiNavigation")
                        .WithMany("Sanphamcts")
                        .HasForeignKey("Maloai")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAMCT__MALOA__0C85DE4D");

                    b.HasOne("Repository.Models.Mau", "MamauNavigation")
                        .WithMany("Sanphamcts")
                        .HasForeignKey("Mamau")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAMCT__MAMAU__08B54D69");

                    b.HasOne("Repository.Models.Size", "MasizeNavigation")
                        .WithMany("Sanphamcts")
                        .HasForeignKey("Masize")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAMCT__MASIZ__3A4CA8FD");

                    b.HasOne("Repository.Models.Sanpham", "MaspNavigation")
                        .WithMany("Sanphamcts")
                        .HasForeignKey("Masp")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAMCT__MASP__09A971A2");

                    b.HasOne("Repository.Models.Thuonghieu", "MathuonghieuNavigation")
                        .WithMany("Sanphamcts")
                        .HasForeignKey("Mathuonghieu")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAMCT__MATHU__0B91BA14");

                    b.HasOne("Repository.Models.Xuatxu", "MaxuatxuNavigation")
                        .WithMany("Sanphamcts")
                        .HasForeignKey("Maxuatxu")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAMCT__MAXUA__0A9D95DB");

                    b.Navigation("MachatlieuNavigation");

                    b.Navigation("MaloaiNavigation");

                    b.Navigation("MamauNavigation");

                    b.Navigation("MasizeNavigation");

                    b.Navigation("MaspNavigation");

                    b.Navigation("MathuonghieuNavigation");

                    b.Navigation("MaxuatxuNavigation");
                });

            modelBuilder.Entity("Repository.Models.Thanhtoan", b =>
                {
                    b.HasOne("Repository.Models.Hoadon", "MahdNavigation")
                        .WithMany("Thanhtoans")
                        .HasForeignKey("Mahd")
                        .IsRequired()
                        .HasConstraintName("FK__THANHTOAN__MAHD__2BFE89A6");

                    b.Navigation("MahdNavigation");
                });

            modelBuilder.Entity("Repository.Models.Chatlieu", b =>
                {
                    b.Navigation("Sanphamcts");
                });

            modelBuilder.Entity("Repository.Models.Chucvu", b =>
                {
                    b.Navigation("Nhanviens");
                });

            modelBuilder.Entity("Repository.Models.Giohangct", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Repository.Models.Hoadon", b =>
                {
                    b.Navigation("Hoadoncts");

                    b.Navigation("Thanhtoans");
                });

            modelBuilder.Entity("Repository.Models.Khachhang", b =>
                {
                    b.Navigation("Danhgia");

                    b.Navigation("Giohang");

                    b.Navigation("Giohangcts");

                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("Repository.Models.Loai", b =>
                {
                    b.Navigation("Sanphamcts");
                });

            modelBuilder.Entity("Repository.Models.Mau", b =>
                {
                    b.Navigation("Sanphamcts");
                });

            modelBuilder.Entity("Repository.Models.Nhanvien", b =>
                {
                    b.Navigation("Hoadons");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Repository.Models.Sanpham", b =>
                {
                    b.Navigation("Sanphamcts");
                });

            modelBuilder.Entity("Repository.Models.Sanphamct", b =>
                {
                    b.Navigation("Danhgia");

                    b.Navigation("Giohangcts");

                    b.Navigation("Hoadoncts");

                    b.Navigation("Productdiscounts");
                });

            modelBuilder.Entity("Repository.Models.Size", b =>
                {
                    b.Navigation("Sanphamcts");
                });

            modelBuilder.Entity("Repository.Models.Thuonghieu", b =>
                {
                    b.Navigation("Sanphamcts");
                });

            modelBuilder.Entity("Repository.Models.Voucher", b =>
                {
                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("Repository.Models.Xuatxu", b =>
                {
                    b.Navigation("Sanphamcts");
                });
#pragma warning restore 612, 618
        }
    }
}
