CREATE DATABASE VERSSCLUB
GO
USE VERSSCLUB
GO
CREATE TABLE KHACHHANG
(
	MAKH VARCHAR(10) NOT NULL PRIMARY KEY,
	HOTEN NVARCHAR(50) NOT NULL,
	GIOITINH BIT NOT NULL,
	SDT VARCHAR(10) NOT NULL,
	DIACHI NVARCHAR(MAX) NOT NULL,
	MATKHAU VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(MAX) NOT NULL,
	NGAYSINH DATE NOT NULL
)
GO
CREATE TABLE CHUCVU
(
	MACHUCVU VARCHAR(10) NOT NULL PRIMARY KEY,
	VAITRO NVARCHAR(50) NOT NULL,
)
GO
CREATE TABLE NHANVIEN
(
	MANV VARCHAR(10) PRIMARY KEY NOT NULL,
	TENKHACHHANG NVARCHAR(50) NULL,
	GIOITINH BIT NOT NULL,
	SDT VARCHAR(10) NOT NULL,
	DIACHI NVARCHAR(MAX) NOT NULL,
	MATKHAU VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(MAX) NOT NULL,
	NGAYSINH DATE NOT NULL,
	TRANGTHAI NVARCHAR(50) NOT NULL,
	MACHUCVU VARCHAR(10) NOT NULL FOREIGN KEY (MACHUCVU) REFERENCES CHUCVU(MACHUCVU)
)
GO
CREATE TABLE SANPHAM
(
	MASP VARCHAR(10) NOT NULL PRIMARY KEY,
	TENSP NVARCHAR(50) NOT NULL,
	TRANGTHAI NVARCHAR(50) NOT NULL
)
GO
CREATE TABLE THUONGHIEU
(
	MATHUONGHIEU VARCHAR(10) NOT NULL PRIMARY KEY,
	TENTHUONGHIEU NVARCHAR(50) NOT NULL,
)
GO
CREATE TABLE LOAI
(
	MALOAI VARCHAR(10) NOT NULL PRIMARY KEY,
	TENLOAI NVARCHAR(50) NOT NULL,
)
GO
CREATE TABLE CHATLIEU
(
	MACHATLIEU VARCHAR(10) NOT NULL PRIMARY KEY,
	TENCHATLIEU NVARCHAR(50) NOT NULL,
)
GO
CREATE TABLE SIZE
(
	MASIZE VARCHAR(10) NOT NULL PRIMARY KEY,
	SIZE VARCHAR(50) NOT NULL,
)
GO
CREATE TABLE MAU
(
	MAMAU VARCHAR(10) NOT NULL PRIMARY KEY,
	MAU NVARCHAR(50) NOT NULL,
)
GO
CREATE TABLE XUATXU
(
	MAXUATXU VARCHAR(10) NOT NULL PRIMARY KEY,
	XUATXU NVARCHAR(50) NOT NULL,
)
GO
CREATE TABLE SANPHAMCT
(
	MASPCT VARCHAR(10) PRIMARY KEY NOT NULL,
	SOLUONG INT NOT NULL,
	GIA FLOAT NOT NULL,
	MACHATLIEU VARCHAR(10) NOT NULL FOREIGN KEY (MACHATLIEU) REFERENCES CHATLIEU(MACHATLIEU),
	MAMAU VARCHAR(10) NOT NULL FOREIGN KEY (MAMAU) REFERENCES MAU(MAMAU),
	TRANGTHAI NVARCHAR(50) NOT NULL,
	IMGURL VARCHAR(MAX) NOT NULL,
	MASP VARCHAR(10) NOT NULL FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
	MAXUATXU VARCHAR(10) NOT NULL FOREIGN KEY (MAXUATXU) REFERENCES XUATXU(MAXUATXU),
	MATHUONGHIEU VARCHAR(10) NOT NULL FOREIGN KEY (MATHUONGHIEU) REFERENCES THUONGHIEU(MATHUONGHIEU),
	MALOAI VARCHAR(10) NOT NULL FOREIGN KEY (MALOAI) REFERENCES LOAI(MALOAI),
	MASIZE VARCHAR(10) NOT NULL FOREIGN KEY (MASIZE) REFERENCES SIZE(MASIZE)
)
GO
CREATE TABLE GIOHANG
(
	MAKH VARCHAR(10) NOT NULL PRIMARY KEY,
	CONSTRAINT FK_GIOHANG_KHACHHANG FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)
)
GO
CREATE TABLE GIOHANGCT
(
	MAGHCT VARCHAR(10) NOT NULL PRIMARY KEY,
	MAKH VARCHAR(10) NOT NULL FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
	MASPCT VARCHAR(10) NOT NULL FOREIGN KEY(MASPCT) REFERENCES SANPHAMCT(MASPCT),
	SOLUONG INT NOT NULL,
	TONGTIEN FLOAT NOT NULL
)
GO
CREATE TABLE VOUCHER
(
	MAGIAMGIA VARCHAR(10) NOT NULL PRIMARY KEY,
	TENMA NVARCHAR(50) NOT NULL,
	BATDAU DATETIME NOT NULL,
	KETTHUC DATETIME NOT NULL,
	TRANGTHAI NVARCHAR(50) NOT NULL,
	PHANTRAMGIAM FLOAT NOT NULL
)
CREATE TABLE KHACHHANGVOUCHER
(
	MAKH VARCHAR(10) NOT NULL,
	MAGIAMGIA VARCHAR(10) NOT NULL,
	CONSTRAINT PK_KHACHHANGVOUCHER PRIMARY KEY(MAKH,MAGIAMGIA),
	CONSTRAINT FK_KHACHHANGVOUCHER_KHACHHANG FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH),
	CONSTRAINT FK_KHACHHANGVOUCHER_VOUCHER FOREIGN KEY(MAGIAMGIA) REFERENCES VOUCHER(MAGIAMGIA)
)
GO
CREATE TABLE DANHGIA
(
	MADANHGIA VARCHAR(10) NOT NULL PRIMARY KEY,
	MAKH VARCHAR(10) NOT NULL FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH),
	MASPCT VARCHAR(10) NOT NULL FOREIGN KEY(MASPCT) REFERENCES SANPHAMCT(MASPCT),
	BINHLUAN NVARCHAR(MAX),
	HINHANH VARCHAR(MAX),
	NGAYDANG DATE NOT NULL,
	SOSAO INT
)
GO
CREATE TABLE [ORDER]
(
	MAORDER VARCHAR(10) NOT NULL PRIMARY KEY,
	MAGHCT VARCHAR(10) NOT NULL FOREIGN KEY(MAGHCT) REFERENCES GIOHANGCT(MAGHCT),
	MANV VARCHAR(10) NOT NULL FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
	NGAYDAT DATETIME NOT NULL,
	TONGTIEN FLOAT NOT NULL,
	TRANGTHAI NVARCHAR(50) NOT NULL
)
GO
CREATE TABLE HOADON
(
	MAHD VARCHAR(10) NOT NULL PRIMARY KEY,
	MAKH VARCHAR(10) NOT NULL FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH),
	MANV VARCHAR(10) NOT NULL FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV),
	MAGIAMGIA VARCHAR(10) NOT NULL FOREIGN KEY(MAGIAMGIA) REFERENCES VOUCHER(MAGIAMGIA),
	GHICHU NVARCHAR(50),
	TONGTIEN FLOAT NOT NULL,
	NGAYTAO DATETIME NOT NULL,
	TRANGTHAI NVARCHAR(50)
)
GO
CREATE TABLE HOADONCT
(
	MAHDCT VARCHAR(10) NOT NULL PRIMARY KEY,
	MAHD VARCHAR(10) NOT NULL FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD),
	MASPCT VARCHAR(10) NOT NULL FOREIGN KEY(MASPCT) REFERENCES SANPHAMCT(MASPCT),
	SOLUONG FLOAT NOT NULL,
	TONGTIEN FLOAT NOT NULL,
	TRANGTHAI NVARCHAR(50) NOT NULL
)
GO
CREATE TABLE THANHTOAN
(
	MATHANHTOAN VARCHAR(10) NOT NULL PRIMARY KEY,
	MAHD VARCHAR(10) NOT NULL FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD),
	PHUONGTHUC NVARCHAR(50) NOT NULL,
	TONGTIEN FLOAT NOT NULL,
	TRANGTHAI NVARCHAR(50) NOT NULL,
	NGAYTHANHTOAN DATETIME NOT NULL
)
GO
CREATE TABLE PRODUCTDISCOUNTS
(
	MADISCOUNTS VARCHAR(10) NOT NULL PRIMARY KEY,
	DISCOUNTSNAME VARCHAR(10) NOT NULL,
	MASPCT VARCHAR(10) NOT NULL FOREIGN KEY(MASPCT) REFERENCES SANPHAMCT(MASPCT),
	BATDAU DATETIME NOT NULL,
	KETTHUC DATETIME NOT NULL,
	PHAMTRAMGIAM FLOAT NOT NULL,
	TRANGTHAI NVARCHAR(50) NOT NULL
)
GO
